export const pythonTokens = [
  "and",
  "as",
  "assert",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "exec",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "None",
  "not",
  "or",
  "pass",
  "print",
  "raise",
  "return",
  "self",
  "try",
  "while",
  "with",
  "yield",

  "int",
  "float",
  "long",
  "complex",
  "hex",

  "abs",
  "all",
  "any",
  "apply",
  "basestring",
  "bin",
  "bool",
  "buffer",
  "bytearray",
  "callable",
  "chr",
  "classmethod",
  "cmp",
  "coerce",
  "compile",
  "complex",
  "delattr",
  "dict",
  "dir",
  "divmod",
  "enumerate",
  "eval",
  "execfile",
  "file",
  "filter",
  "format",
  "frozenset",
  "getattr",
  "globals",
  "hasattr",
  "hash",
  "help",
  "id",
  "input",
  "intern",
  "isinstance",
  "issubclass",
  "iter",
  "len",
  "locals",
  "list",
  "map",
  "max",
  "memoryview",
  "min",
  "next",
  "object",
  "oct",
  "open",
  "ord",
  "pow",
  "print",
  "property",
  "reversed",
  "range",
  "raw_input",
  "reduce",
  "reload",
  "repr",
  "reversed",
  "round",
  "set",
  "setattr",
  "slice",
  "sorted",
  "staticmethod",
  "str",
  "sum",
  "super",
  "tuple",
  "type",
  "unichr",
  "unicode",
  "vars",
  "xrange",
  "zip",
  "True",
  "False",
  "__dict__",
  "__methods__",
  "__members__",
  "__class__",
  "__bases__",
  "__name__",
  "__mro__",
  "__subclasses__",
  "__init__",
  "__import__",
];

export const pytugaTokens = [
  "a",
  "de",
  "repetir",
  "cada",
  "vezes",
  "mostrar",
  "mostre",
  "enquanto",
  "para",
  "quebre",
  "quebrar",
  "continuar",
  "para_cada",
  "se",
  "senão",
  "senao",
  "ou_então_se",
  "ou_entao_se",
  "ou_se",
  "Falso",
  "falso",
  "Verdadeiro",
  "verdadeiro",
  "nulo",
  "Nulo",
  "é",
  "eh",
  "e",
  "ou",
  "não",
  "nao",
  "em",
  "na",
  "no",
  "como",
  "função",
  "funcao",
  "definir",
  "defina",
  "retorne",
  "retornar",
  "gere",
  "gerar",
  "tente",
  "tentar",
  "exceção",
  "excecao",
  "finalmente",
  "levante_error",
  "levantar_erro",
  "apague",
  "apagar",
  "prossiga",
  "prosseguir",
  "classe",
  "importe",
  "importar",
  "usando",
  "até",
  "ateh",
  "faça:",
  "faca:",
  "fazer:",
  "para cada",
  "então faça:",
  "então:",
  "entao faca:",
  "entao:",
  "ou então se",
  "ou entao se",
  "ou se",
  "definir função",
  "definir funcao",
  "defina função",
  "defina funcao",
  "definir classe",
  "defina classe",
];

export const tugalinhaTranslations = {
  adicionar_forma: "addshape",
  animação: "animation",
  cor_fundo: "bgcolor",
  imagem_fundo: "bgpic",
  tchau: "bye",
  limpar_tela: "clearscreen",
  modo_cor: "colormode",
  atraso: "delay",
  sair_ao_clicar: "exitonclick",
  obter_tela: "getcanvas",
  obter_formas: "getshapes",
  ouvir: "listen",
  modo: "mode",
  entrada_número: "numinput",
  na_tecla: "onkey",
  ao_pressionar_tecla: "onkeypress",
  ao_soltar_tecla: "onkeyrelease",
  ao_clicar_tela: "onscreenclick",
  temporizador: "ontimer",
  registrar_forma: "register_shape",
  redefinir_tela: "resetscreen",
  salvar: "save",
  tamanho_tela: "screensize",
  configurar: "setup",
  definir_coordenadas_mundiais: "setworldcoordinates",
  svg: "svg",
  entrada_de_texto: "textinput",
  título: "title",
  rastreador: "tracer",
  pincéis: "turtles",
  atualizar: "update",
  altura_janela: "window_height",
  largura_janela: "window_width",

  voltar: "back",
  atrás: "backward",
  começar_preenchimento: "begin_fill",
  começar_polígono: "begin_poly",
  vt: "bk",
  círculo: "circle",
  limpar: "clear",
  limpar_marcação: "clearstamp",
  limpar_marcações: "clearstamps",
  clonar: "clone",
  cor: "color",
  graus: "degrees",
  distância: "distance",
  ponto: "dot",
  baixar: "down",
  terminar_preenchimento: "end_fill",
  terminar_polígono: "end_poly",
  ft: "fd",
  cor_preenchimento: "fillcolor",
  preenchimento: "filling",
  frente: "forward",
  obter_polígono: "get_poly",
  pegue_pincél: "getpen",
  obter_tela: "getscreen",
  obter_forma_polígono: "get_shapepoly",
  obter_pincél: "getturtle",
  vai_para: "goto",
  cabeçalho: "heading",
  ocultar_pincél: "hideturtle",
  origem: "home",
  ht: "ht",
  pincél_baixo: "isdown",
  está_visível: "isvisible",
  esquerda: "left",
  esq: "lt",
  ao_clicar: "onclick",
  ao_arrastar: "ondrag",
  ao_soltar: "onrelease",
  abaixar: "pd",
  caneta: "pen",
  cor_pincél: "pencolor",
  abaixar_pincél: "pendown",
  espessura: "pensize",
  levantar_pincél: "penup",
  posição: "position",
  radianos: "radians",
  direita: "right",
  redefinir: "reset",
  redimensionamento: "resizemode",
  dir: "rt",
  definir_cabeçalho: "setheading",
  definir_posição: "setpos",
  definir_posição: "setposition",
  definir_inclinação: "settiltangle",
  definir_buffer_de_desfazer: "setundobuffer",
  definir_x: "setx",
  definir_y: "sety",
  forma: "shape",
  tamanho_da_forma: "shapesize",
  transformar_forma: "shapetransform",
  ângulo_de_corte: "shearfactor",
  mostrar_pincél: "showturtle",
  velocidade: "speed",
  mt: "st",
  carimbar: "stamp",
  inclinar: "tilt",
  inclinação_ângulo: "tiltangle",
  angulo_para: "towards",
  tamanho_pincél: "turtlesize",
  desfazer: "undo",
  desfazer_entradas_de_buffer: "undobufferentries",
  levantar: "up",
  largura: "width",
  escrever: "write",
  x_coordenada: "xcor",
  y_coordenada: "ycor",
  feito: "done",
  loop_principal: "mainloop",
  reiniciar: "restart",
  repetir_cena: "replay_scene",
  Tugalinha: "Turtle",
  Tela: "Screen",
};

export const tugalinhaTokens = Object.keys(tugalinhaTranslations);
export const turtleTokens = Object.values(tugalinhaTranslations);
